---
- name: Copy config to master
  template:
    src: config.yml
    dest: /tmp/kubeadm_conf.yml

- name: kubeadm init on master
  command: kubeadm init --config /tmp/kubeadm_conf.yml 
  args:
    creates: /etc/kubernetes/admin.conf

- firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
  failed_when: false

- name: Create /root/.kube
  file:
    path: /root/.kube
    state: directory

- name: Create .kube config (root)
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root

- name: Create /home/vagrant/.kube
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
  tags:
    - vagrant-only

- name: Create .kube config (vagrant)
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    owner: vagrant
    group: vagrant
  tags:
    - vagrant-only
- name: Apply a pod network (flannel)
  shell: >
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

- block:
    - name: Wait for DNS to be ready
      command: >
              kubectl get -n kube-system svc/kube-dns
              -o jsonpath='{.spec.clusterIP}'
      register: dnsaddr
    - wait_for:
        host: "{{ dnsaddr.stdout }}"
        port: 53
        state: started
        timeout: 600
